# Generated by Django 3.2.8 on 2021-10-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='qestion',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='qestion_text',
            new_name='question_text',
        ),
    ]
